apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-crda
  namespace: 3scale-project
spec:
  imageStreamTagImportInsecure: false
  resourceRequirementsEnabled: true
  system:
    appSpec: {}
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: 3scale-aws-s3
    sidekiqSpec: {}
    sphinxSpec: {}
  appLabel: 3scale-api-management
  zync:
    appSpec: {}
    queSpec: {}
  backend:
    cronSpec: {}
    listenerSpec: {}
    workerSpec: {}
  tenantName: 3scale
  apicast:
    managementAPI: status
    openSSLVerify: false
    registryURL: 'http://apicast-staging:8090/policies'
    responseCodes: true
  wildcardDomain: <WILDCARD_DOMAIN>